services:
  postgres:
    image: postgres:latest
    env_file: '.env'
    environment:
      - NODE_ENV=production
    expose:
      - '5432'
    volumes:
      - pg_dev_data:/var/lib/postgresql/data
    networks:
      - writrmd_network

  writrmd:
    image: writrmd:dev
    restart: unless-stopped
    networks:
      - writrmd_network
    ports:
      - '3000:3000'
    env_file: '.env'
    volumes:
      - writrmd_dev_data:/app/content
    depends_on:
      - postgres

volumes:
  writrmd_dev_data:
  pg_dev_data:

networks:
  writrmd_network:
    driver: bridge
