services:
  postgres:
    image: postgres:latest
    env_file: .env
    expose:
      - '5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - writrmd_network

  writrmd:
    image: ghcr.io/jamesspearsv/writrmd:latest
    restart: unless-stopped
    networks:
      - writrmd_network
    expose:
      - '3000'
    env_file: .env # MAKE SURE THIS FILE IS PRESENT AND ACCURATE
    environment:
      - NODE_ENV=production
      - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - writrmd-data:/app/content
    depends_on:
      - postgres

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - writrmd_network
    depends_on:
      - writrmd

volumes:
  caddy_data:
  caddy_config:
  writrmd-data:
  pg_data:

networks:
  writrmd_network:
    driver: bridge
